services:
  arvefordelerenwebapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/src 
      - /src/bin
      - /src/obj
      - /root/.aspnet/DataProtection-Keys 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    stdin_open: true
    tty: true