FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ArvefordelerenWebApp.csproj", "./"]
RUN dotnet restore "ArvefordelerenWebApp.csproj"
COPY . .

RUN dotnet dev-certs https --trust
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]